language: go

env:
  global:
  - OWNER=containerum
  - NAME=containerum
  - IMAGE_NAME=$OWNER/$NAME
  - MUSEUM=https://charts.containerum.io

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push
  - go get github.com/mikefarah/yq
  - sudo apt-get install jq

script:
  - helm repo add containerum ${MUSEUM}
  - helm package charts/$NAME --version="1.0" --dependency-update
  - rm $NAME-${TRAVIS_TAG}.tgz

before_deploy:
  - yq write --inplace charts/$NAME/values.yaml image.tag "${TRAVIS_TAG}"
  - mkdir -p /tmp/charts
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination /tmp/charts
  - helm repo add chartmuseum ${MUSEUM}

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
      tags: true
  - provider: script
    script: helm push -u ${HELM_USER} -p ${HELM_PASSWORD} "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz" chartmuseum
    on:
      tags: true
