sudo: required

language: go

env:
  global:
  - OWNER=containerum
  - NAME=containerum
  - IMAGE_NAME=$OWNER/$NAME
  - MUSEUM=https://charts.containerum.io

before_install:
- go generate -v ./embark

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push

script:
- go test ./embark/...
  - go build -v -o ./build/embark_$(go env GOOS)_$(go env GOHOSTARCH) ./embark/cmd/embark
  - helm repo add containerum ${MUSEUM}
  - helm package charts/$NAME --version="1.0" --dependency-update
  - rm $NAME-1.0.tgz

before_deploy:
  - mkdir -p /tmp/charts
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination /tmp/charts

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: helm push -u ${HELM_USER} -p ${HELM_PASSWORD} "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz" containerum
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: ./build/*
    skip_cleanup: true
    on:
      tags: true

notifications:
  webhooks:
    urls:
    - https://integrations.bonbotics.io/travis/webhook/Vv1nUUPlGoIq3Baehmzw6DsGEbwL0F4xZRhsBHk0Vdk
    on_success: always
    on_failure: always
    on_start: never