sudo: required

language: go

env:
  global:
  - OWNER=containerum
  - NAME=containerum
  - IMAGE_NAME=$OWNER/$NAME
  - MUSEUM=https://charts.containerum.io
  - CHANGE_MINIKUBE_NONE_USER=true


before_script:
  - echo $TEST_KUBERNETES_CERT > $HOME/.ssh/id_rsa
  - ssh -o "StrictHostKeyChecking no" $KUBERNETES_TEST_USERNAME@$KUBERNETES_TEST_CLUSTER_ADDR -p $KUBERNETES_TEST_PORT exit #test ssh connection
#  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl
#  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/
#  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#  - chmod +x minikube && sudo mv minikube /usr/local/bin/
#  - sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
#  - minikube update-context
#  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'
#  - until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
  - go test ./embark/...
  - go build -v -o ./build/embark_$(go env GOOS)_$(go env GOHOSTARCH) ./embark/cmd/embark
  - helm repo add containerum ${MUSEUM}
  - helm package charts/$NAME --version="1.0" --dependency-update
  - rm $NAME-1.0.tgz

before_install:

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push

before_deploy:
  - mkdir -p /tmp/charts
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination /tmp/charts
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: helm push -u ${HELM_USER} -p ${HELM_PASSWORD} "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz" containerum
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: ./build/*
    skip_cleanup: true
    on:
      tags: true

notifications:
  webhooks:
    urls:
      - "https://integrations.bonbotics.io/travis/webhook/Vv1nUUPlGoIq3Baehmzw6DsGEbwL0F4xZRhsBHk0Vdk"
    on_success: always
    on_failure: always
    on_start: never