sudo: required

language: go

env:
  global:
  - OWNER=containerum
  - NAME=containerum
  - IMAGE_NAME=$OWNER/$NAME
  - MUSEUM=https://charts.containerum.io

before_install:
- go install -v ./embark/vendor/github.com/UnnoTed/fileb0x
- go generate -v ./embark

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push

script:
  - go build -v -o ./build/embark ./embark/cmd/embark
  - helm repo add containerum ${MUSEUM}
  - helm package charts/$NAME --version="1.0" --dependency-update
  - rm $NAME-1.0.tgz

before_deploy:
  - mkdir -p /tmp/charts
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination /tmp/charts

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: helm push -u ${HELM_USER} -p ${HELM_PASSWORD} "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz" containerum
    skip_cleanup: true
    on:
      tags: true
