containerum:
  version: 1.6.1
  dependson: [mail]
  objects:
  - service
  - ingress
  values:
    CONTAINERUM_VERSION: 1.6.1

postrgesql:
  version: 1.2.2
  objects:
  - "deployment.yaml"

mail:
  version: 0.9.6
  objects:
  - deployment.yaml
  - service
  - ingress
  - svc
