dependencies:
  - name: postgresql
    repository: https://charts.containerum.io
    version: 0.15.0
    tags:
      - db
      - postgresql
      - platform
  - name: mongodb
    version: "3.0.4"
    repository: https://charts.containerum.io
    tags:
      - db
      - mongo
      - platform
  - name: api-gateway
    version: "v1.0.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - gateway
      - platform
  - name: user-manager
    version: "v1.0.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - user
      - platform
  - name: resource
    version: "v1.0.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - resource
      - platform
  - name: permissions
    version: "v1.0.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - permissions
      - platform
  - name: kube
    version: "v1.0.7-rc.0"
    repository: https://charts.containerum.io
    tags:
      - back
      - kube
      - platform
  - name: auth
    version: "v1.0.3"
    repository: https://charts.containerum.io
    tags:
      - back
      - auth
      - platform
  - name: mail
    version: "v1.0.3"
    repository: https://charts.containerum.io
    tags:
      - back
      - mail
      - platform
  - name: ui
    version: "v1.0.7-rc.2"
    repository: https://charts.containerum.io
    tags:
      - front
      - ui
      - platform
  - name: nodemetrics
    version: "v1.0.3"
    repository: https://charts.containerum.io
    tags:
      - monitoring
      - nodemetrics
      - platform
  - name: volume
    version: "v1.0.2"
    repository: https://charts.containerum.io
    tags:
      - back
      - volume
      - platform
  - name: solutions
    version: "v1.0.2"
    repository: https://charts.containerum.io
    tags:
      - back
      - solutions
      - platform
  - name: kube-importer
    version: "v0.0.5"
    repository: https://charts.containerum.io
    tags:
      - back
      - kube-importer
      - platform
