tags:
  db: false
  platform: true
  platformdb: true

ingress:
  ui:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - local.containerum.io
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  api:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - api.local.containerum.io
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


ui:
  env:
    local:
      ## Default user country
      COUNTRY: US
      ## for HTTPS use: ssl
      API_PROTOCOL_TYPE: no-ssl
      API_PORT: null
    global:
      API_HOST: api.local.containerum.io
      RECAPTCHA: null

mail:
  persistence:
    enabled: false

auth:
  persistence:
    enabled: false

user-manager:
  tags:
    platformdb: true
  env:
    global:
      CH_USER_PG_DBNAME: containerum
      CH_USER_PG_LOGIN: postgres
    local:
      CH_USER_PG_ADDR: null
      CH_USER_MAIL_URL: null
      CH_USER_AUTH_GRPC_ADDR: null
      CH_USER_PERMISSIONS_URL: null
      ## if CH_USER_ADMIN_PASSWORD null then admin doesn't creates
      CH_USER_ADMIN_PASSWORD: verystrongpassword

permissions:
  tags:
    platformdb: true
  env:
    global:
      DB_BASE: containerum
      DB_USER: postgres
    local:
      DB_HOST: null

resource:
  tags:
    platformdb: true
  env:
    global:
      CH_RESOURCE_MONGO_DB: containerum
      CH_RESOURCE_MONGO_LOGIN: mongo
    local:
      CH_RESOURCE_MONGO_ADDR: null

api-gateway:
  env:
    local:
      SERVICE_HOST_PREFIX: release-name
      GRPC_AUTH_ADDRESS: null

auth:
  persistence:
    enabled: false

postgresql:
  persistence:
    enabled: false
  postgresDatabase: containerum
  # postgresUser: postgres
  # postgresPassword: password


mongodb:
  persistence:
    enabled: false
  mongodbDatabase: containerum
  mongodbUsername: mongo
  # mongodbPassword: password
