
required = [
#     "k8s.io/api",
#     "k8s.io/apimachinery",
#     "k8s.io/kubernetes",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "k8s.io/helm"
  version = "~2.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "089cf0d1f58c48b3d14c76882a37708efe549e7b"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "~2.2.1"

[[constraint]]
  name = "github.com/octago/sflags"
  version = "~0.2.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~6.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

#####################################
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"