
required = ["github.com/UnnoTed/fileb0x"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "k8s.io/helm"
  version = "~v2.9.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "089cf0d1f58c48b3d14c76882a37708efe549e7b"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "~2.2.1"

[[constraint]]
  name = "github.com/octago/sflags"
  version = "~0.2.0"

#[[constraint]]
#  name = "k8s.io/client-go"
#  version = "kubernetes-1.10.0"

#[[constraint]]
#  name = "k8s.io/api"
#  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~v1.0.6"

[[constraint]]
  name = "github.com/go-playground/validator"
  version = "~9.21.0"

[[constraint]]
  name = "github.com/ericchiang/k8s"
  version = "~v1.2.0"

[[constraint]]
  name = "github.com/thoas/go-funk"
  revision = "1060394a7713649853efcb78f5c929b877efbbbb"

#####################################


#[[override]]
#  name = "k8s.io/kubernetes
#  version = "~1.9.3"

#[[override]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.9.3"

#[[override]]
#  name = "github.com/docker/docker"
#  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

#[[override]]
#  name = "github.com/russross/blackfriday"
#  version = "~v1.4-2-g300106c"
[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.0.0"
